
// This file has been generated by the GUI designer. Do not modify.
namespace UberDespatch
{
	public partial class CarrierPOSTWindow
	{
		private global::Gtk.VBox CarrierLayout;
		
		private global::Gtk.Frame APIFrame;
		
		private global::Gtk.Alignment APIAlignment;
		
		private global::Gtk.VBox APILayout;
		
		private global::Gtk.Label CarrierDescriptionLabel;
		
		private global::Gtk.HBox CarrierSelectionLayout;
		
		private global::Gtk.ComboBox CarrierSelectionCombo;
		
		private global::Gtk.HBox PrinterProfileControlsLayout;
		
		private global::Gtk.Button CarrierRemoveButton;
		
		private global::Gtk.Button CarrierAddButton;
		
		private global::Gtk.Image CarrierImage;
		
		private global::Gtk.HBox CarrierNameLayout;
		
		private global::Gtk.Label CarrierNameLabel;
		
		private global::Gtk.Entry CarrierNameEntry;
		
		private global::Gtk.HBox URLLayout;
		
		private global::Gtk.Label URLLabel;
		
		private global::Gtk.Entry URLEntry;
		
		private global::Gtk.HBox PrinterProfileLayout;
		
		private global::Gtk.Label PrinterProfileLabel;
		
		private global::Gtk.ComboBox PrinterProfileSelectionCombo;
		
		private global::Gtk.Label CarrierLabel;
		
		private global::Gtk.Frame HiveDetailsFrame;
		
		private global::Gtk.Alignment HiveDetailsAlignment;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView AdditionalPOSTTextView;
		
		private global::Gtk.Label HiveDetailsLabel;
		
		private global::Gtk.Button CarrierSaveButton;
		
		private global::Gtk.HBox MainControlsLayout;
		
		private global::Gtk.Alignment MainControlsSpacerAlignment;
		
		private global::Gtk.Button CancelButton;
		
		private global::Gtk.Button ConfirmButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UberDespatch.CarrierPOSTWindow
			this.Name = "UberDespatch.CarrierPOSTWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Hive Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(8));
			// Container child UberDespatch.CarrierPOSTWindow.Gtk.Container+ContainerChild
			this.CarrierLayout = new global::Gtk.VBox ();
			this.CarrierLayout.Name = "CarrierLayout";
			this.CarrierLayout.Spacing = 6;
			// Container child CarrierLayout.Gtk.Box+BoxChild
			this.APIFrame = new global::Gtk.Frame ();
			this.APIFrame.Name = "APIFrame";
			this.APIFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			this.APIFrame.BorderWidth = ((uint)(8));
			// Container child APIFrame.Gtk.Container+ContainerChild
			this.APIAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.APIAlignment.Name = "APIAlignment";
			this.APIAlignment.LeftPadding = ((uint)(12));
			// Container child APIAlignment.Gtk.Container+ContainerChild
			this.APILayout = new global::Gtk.VBox ();
			this.APILayout.Name = "APILayout";
			this.APILayout.Spacing = 6;
			// Container child APILayout.Gtk.Box+BoxChild
			this.CarrierDescriptionLabel = new global::Gtk.Label ();
			this.CarrierDescriptionLabel.WidthRequest = 512;
			this.CarrierDescriptionLabel.Name = "CarrierDescriptionLabel";
			this.CarrierDescriptionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Hive carriers can/will support various shipping services such as Amazon Fullfilled orders (Amazon Prime).");
			this.CarrierDescriptionLabel.UseMarkup = true;
			this.CarrierDescriptionLabel.Wrap = true;
			this.APILayout.Add (this.CarrierDescriptionLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.APILayout [this.CarrierDescriptionLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child APILayout.Gtk.Box+BoxChild
			this.CarrierSelectionLayout = new global::Gtk.HBox ();
			this.CarrierSelectionLayout.Name = "CarrierSelectionLayout";
			this.CarrierSelectionLayout.Spacing = 6;
			// Container child CarrierSelectionLayout.Gtk.Box+BoxChild
			this.CarrierSelectionCombo = global::Gtk.ComboBox.NewText ();
			this.CarrierSelectionCombo.Name = "CarrierSelectionCombo";
			this.CarrierSelectionLayout.Add (this.CarrierSelectionCombo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.CarrierSelectionLayout [this.CarrierSelectionCombo]));
			w2.Position = 0;
			this.APILayout.Add (this.CarrierSelectionLayout);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.APILayout [this.CarrierSelectionLayout]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child APILayout.Gtk.Box+BoxChild
			this.PrinterProfileControlsLayout = new global::Gtk.HBox ();
			this.PrinterProfileControlsLayout.Name = "PrinterProfileControlsLayout";
			this.PrinterProfileControlsLayout.Spacing = 6;
			// Container child PrinterProfileControlsLayout.Gtk.Box+BoxChild
			this.CarrierRemoveButton = new global::Gtk.Button ();
			this.CarrierRemoveButton.WidthRequest = 150;
			this.CarrierRemoveButton.HeightRequest = 40;
			this.CarrierRemoveButton.CanFocus = true;
			this.CarrierRemoveButton.Name = "CarrierRemoveButton";
			this.CarrierRemoveButton.UseUnderline = true;
			this.CarrierRemoveButton.Label = global::Mono.Unix.Catalog.GetString ("Remove Carrier");
			this.PrinterProfileControlsLayout.Add (this.CarrierRemoveButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.PrinterProfileControlsLayout [this.CarrierRemoveButton]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child PrinterProfileControlsLayout.Gtk.Box+BoxChild
			this.CarrierAddButton = new global::Gtk.Button ();
			this.CarrierAddButton.WidthRequest = 150;
			this.CarrierAddButton.HeightRequest = 40;
			this.CarrierAddButton.CanFocus = true;
			this.CarrierAddButton.Name = "CarrierAddButton";
			this.CarrierAddButton.UseUnderline = true;
			this.CarrierAddButton.Label = global::Mono.Unix.Catalog.GetString ("Add Carrier");
			this.PrinterProfileControlsLayout.Add (this.CarrierAddButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.PrinterProfileControlsLayout [this.CarrierAddButton]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.APILayout.Add (this.PrinterProfileControlsLayout);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.APILayout [this.PrinterProfileControlsLayout]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child APILayout.Gtk.Box+BoxChild
			this.CarrierImage = new global::Gtk.Image ();
			this.CarrierImage.WidthRequest = 150;
			this.CarrierImage.HeightRequest = 50;
			this.CarrierImage.Name = "CarrierImage";
			this.APILayout.Add (this.CarrierImage);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.APILayout [this.CarrierImage]));
			w7.Position = 3;
			// Container child APILayout.Gtk.Box+BoxChild
			this.CarrierNameLayout = new global::Gtk.HBox ();
			this.CarrierNameLayout.Name = "CarrierNameLayout";
			this.CarrierNameLayout.Spacing = 6;
			// Container child CarrierNameLayout.Gtk.Box+BoxChild
			this.CarrierNameLabel = new global::Gtk.Label ();
			this.CarrierNameLabel.WidthRequest = 200;
			this.CarrierNameLabel.Name = "CarrierNameLabel";
			this.CarrierNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.CarrierNameLabel.Wrap = true;
			this.CarrierNameLabel.SingleLineMode = true;
			this.CarrierNameLayout.Add (this.CarrierNameLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.CarrierNameLayout [this.CarrierNameLabel]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child CarrierNameLayout.Gtk.Box+BoxChild
			this.CarrierNameEntry = new global::Gtk.Entry ();
			this.CarrierNameEntry.TooltipMarkup = "The filename for the Hive input file. This should match the setting on Hive. ";
			this.CarrierNameEntry.CanFocus = true;
			this.CarrierNameEntry.Name = "CarrierNameEntry";
			this.CarrierNameEntry.IsEditable = true;
			this.CarrierNameEntry.InvisibleChar = '•';
			this.CarrierNameLayout.Add (this.CarrierNameEntry);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.CarrierNameLayout [this.CarrierNameEntry]));
			w9.Position = 1;
			this.APILayout.Add (this.CarrierNameLayout);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.APILayout [this.CarrierNameLayout]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			// Container child APILayout.Gtk.Box+BoxChild
			this.URLLayout = new global::Gtk.HBox ();
			this.URLLayout.Name = "URLLayout";
			this.URLLayout.Spacing = 6;
			// Container child URLLayout.Gtk.Box+BoxChild
			this.URLLabel = new global::Gtk.Label ();
			this.URLLabel.WidthRequest = 200;
			this.URLLabel.Name = "URLLabel";
			this.URLLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("URL");
			this.URLLabel.Wrap = true;
			this.URLLabel.SingleLineMode = true;
			this.URLLayout.Add (this.URLLabel);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.URLLayout [this.URLLabel]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child URLLayout.Gtk.Box+BoxChild
			this.URLEntry = new global::Gtk.Entry ();
			this.URLEntry.TooltipMarkup = "The filename for the Hive input file. This should match the setting on Hive. ";
			this.URLEntry.CanFocus = true;
			this.URLEntry.Name = "URLEntry";
			this.URLEntry.IsEditable = true;
			this.URLEntry.InvisibleChar = '•';
			this.URLLayout.Add (this.URLEntry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.URLLayout [this.URLEntry]));
			w12.Position = 1;
			this.APILayout.Add (this.URLLayout);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.APILayout [this.URLLayout]));
			w13.Position = 5;
			w13.Expand = false;
			w13.Fill = false;
			// Container child APILayout.Gtk.Box+BoxChild
			this.PrinterProfileLayout = new global::Gtk.HBox ();
			this.PrinterProfileLayout.Name = "PrinterProfileLayout";
			this.PrinterProfileLayout.Spacing = 6;
			// Container child PrinterProfileLayout.Gtk.Box+BoxChild
			this.PrinterProfileLabel = new global::Gtk.Label ();
			this.PrinterProfileLabel.WidthRequest = 200;
			this.PrinterProfileLabel.Name = "PrinterProfileLabel";
			this.PrinterProfileLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Printer Profile");
			this.PrinterProfileLabel.Wrap = true;
			this.PrinterProfileLabel.SingleLineMode = true;
			this.PrinterProfileLayout.Add (this.PrinterProfileLabel);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.PrinterProfileLayout [this.PrinterProfileLabel]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child PrinterProfileLayout.Gtk.Box+BoxChild
			this.PrinterProfileSelectionCombo = global::Gtk.ComboBox.NewText ();
			this.PrinterProfileSelectionCombo.Name = "PrinterProfileSelectionCombo";
			this.PrinterProfileLayout.Add (this.PrinterProfileSelectionCombo);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.PrinterProfileLayout [this.PrinterProfileSelectionCombo]));
			w15.Position = 1;
			this.APILayout.Add (this.PrinterProfileLayout);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.APILayout [this.PrinterProfileLayout]));
			w16.Position = 6;
			w16.Expand = false;
			w16.Fill = false;
			this.APIAlignment.Add (this.APILayout);
			this.APIFrame.Add (this.APIAlignment);
			this.CarrierLabel = new global::Gtk.Label ();
			this.CarrierLabel.Name = "CarrierLabel";
			this.CarrierLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>POST Carriers</b>");
			this.CarrierLabel.UseMarkup = true;
			this.APIFrame.LabelWidget = this.CarrierLabel;
			this.CarrierLayout.Add (this.APIFrame);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.CarrierLayout [this.APIFrame]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child CarrierLayout.Gtk.Box+BoxChild
			this.HiveDetailsFrame = new global::Gtk.Frame ();
			this.HiveDetailsFrame.Name = "HiveDetailsFrame";
			this.HiveDetailsFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child HiveDetailsFrame.Gtk.Container+ContainerChild
			this.HiveDetailsAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.HiveDetailsAlignment.Name = "HiveDetailsAlignment";
			this.HiveDetailsAlignment.LeftPadding = ((uint)(12));
			// Container child HiveDetailsAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.AdditionalPOSTTextView = new global::Gtk.TextView ();
			this.AdditionalPOSTTextView.TooltipMarkup = "Enter the template used by Hive here. {Tags} will be replaced with order data.";
			this.AdditionalPOSTTextView.HeightRequest = 60;
			this.AdditionalPOSTTextView.CanFocus = true;
			this.AdditionalPOSTTextView.Name = "AdditionalPOSTTextView";
			this.AdditionalPOSTTextView.AcceptsTab = false;
			this.AdditionalPOSTTextView.LeftMargin = 4;
			this.AdditionalPOSTTextView.RightMargin = 4;
			this.GtkScrolledWindow.Add (this.AdditionalPOSTTextView);
			this.HiveDetailsAlignment.Add (this.GtkScrolledWindow);
			this.HiveDetailsFrame.Add (this.HiveDetailsAlignment);
			this.HiveDetailsLabel = new global::Gtk.Label ();
			this.HiveDetailsLabel.Name = "HiveDetailsLabel";
			this.HiveDetailsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Additional POST Paramters</b>");
			this.HiveDetailsLabel.UseMarkup = true;
			this.HiveDetailsFrame.LabelWidget = this.HiveDetailsLabel;
			this.CarrierLayout.Add (this.HiveDetailsFrame);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.CarrierLayout [this.HiveDetailsFrame]));
			w23.Position = 1;
			// Container child CarrierLayout.Gtk.Box+BoxChild
			this.CarrierSaveButton = new global::Gtk.Button ();
			this.CarrierSaveButton.WidthRequest = 150;
			this.CarrierSaveButton.HeightRequest = 40;
			this.CarrierSaveButton.CanFocus = true;
			this.CarrierSaveButton.Name = "CarrierSaveButton";
			this.CarrierSaveButton.UseUnderline = true;
			this.CarrierSaveButton.Label = global::Mono.Unix.Catalog.GetString ("Save Carrier");
			this.CarrierLayout.Add (this.CarrierSaveButton);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.CarrierLayout [this.CarrierSaveButton]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child CarrierLayout.Gtk.Box+BoxChild
			this.MainControlsLayout = new global::Gtk.HBox ();
			this.MainControlsLayout.Name = "MainControlsLayout";
			this.MainControlsLayout.Spacing = 6;
			// Container child MainControlsLayout.Gtk.Box+BoxChild
			this.MainControlsSpacerAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.MainControlsSpacerAlignment.Name = "MainControlsSpacerAlignment";
			this.MainControlsLayout.Add (this.MainControlsSpacerAlignment);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.MainControlsLayout [this.MainControlsSpacerAlignment]));
			w25.Position = 0;
			// Container child MainControlsLayout.Gtk.Box+BoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.WidthRequest = 150;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			global::Gtk.Image w26 = new global::Gtk.Image ();
			w26.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Icons/png/no-small.png"));
			this.CancelButton.Image = w26;
			this.MainControlsLayout.Add (this.CancelButton);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.MainControlsLayout [this.CancelButton]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child MainControlsLayout.Gtk.Box+BoxChild
			this.ConfirmButton = new global::Gtk.Button ();
			this.ConfirmButton.WidthRequest = 150;
			this.ConfirmButton.CanFocus = true;
			this.ConfirmButton.Name = "ConfirmButton";
			this.ConfirmButton.UseUnderline = true;
			this.ConfirmButton.Label = global::Mono.Unix.Catalog.GetString ("Ok");
			global::Gtk.Image w28 = new global::Gtk.Image ();
			w28.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Icons/png/apply-small.png"));
			this.ConfirmButton.Image = w28;
			this.MainControlsLayout.Add (this.ConfirmButton);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.MainControlsLayout [this.ConfirmButton]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.CarrierLayout.Add (this.MainControlsLayout);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.CarrierLayout [this.MainControlsLayout]));
			w30.Position = 3;
			w30.Expand = false;
			w30.Fill = false;
			this.Add (this.CarrierLayout);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 560;
			this.DefaultHeight = 532;
			this.Show ();
			this.CarrierSelectionCombo.Changed += new global::System.EventHandler (this.OnCarrierComboChanged);
			this.CarrierRemoveButton.Released += new global::System.EventHandler (this.OnRemoveCarrierButtonReleased);
			this.CarrierAddButton.Released += new global::System.EventHandler (this.OnAddCarrierButtonReleased);
			this.CarrierSaveButton.Released += new global::System.EventHandler (this.OnSaveCarrierButtonReleased);
			this.CancelButton.Released += new global::System.EventHandler (this.OnCancelButtonReleased);
			this.ConfirmButton.Released += new global::System.EventHandler (this.OnConfirmButtonReleased);
		}
	}
}
