
// This file has been generated by the GUI designer. Do not modify.
namespace UberDespatch
{
	public partial class CarrierHiveWindow
	{
		private global::Gtk.VBox CarrierLayout;

		private global::Gtk.Frame APIFrame;

		private global::Gtk.Alignment APIAlignment;

		private global::Gtk.VBox APILayout;

		private global::Gtk.Image CarrierImage;

		private global::Gtk.Label CarrierDescriptionLabel;

		private global::Gtk.HBox HiveURLLayout;

		private global::Gtk.Label HiveURLLabel;

		private global::Gtk.Entry InputHiveURLEntry;

		private global::Gtk.HBox HiveURLLayout1;

		private global::Gtk.Label PrinterProfileLabel;

		private global::Gtk.ComboBox PrinterProfileSelectionCombo;

		private global::Gtk.Label CarrierLabel;

		private global::Gtk.Frame HiveDetailsFrame;

		private global::Gtk.Alignment HiveDetailsAlignment;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView HiveDetailsTextView;

		private global::Gtk.Label HiveDetailsLabel;

		private global::Gtk.HBox MainControlsLayout;

		private global::Gtk.Alignment MainControlsSpacerAlignment;

		private global::Gtk.Button CancelButton;

		private global::Gtk.Button ConfirmButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget UberDespatch.CarrierHiveWindow
			this.Name = "UberDespatch.CarrierHiveWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Hive Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(8));
			// Container child UberDespatch.CarrierHiveWindow.Gtk.Container+ContainerChild
			this.CarrierLayout = new global::Gtk.VBox();
			this.CarrierLayout.Name = "CarrierLayout";
			this.CarrierLayout.Spacing = 6;
			// Container child CarrierLayout.Gtk.Box+BoxChild
			this.APIFrame = new global::Gtk.Frame();
			this.APIFrame.Name = "APIFrame";
			this.APIFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			this.APIFrame.BorderWidth = ((uint)(8));
			// Container child APIFrame.Gtk.Container+ContainerChild
			this.APIAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.APIAlignment.Name = "APIAlignment";
			this.APIAlignment.LeftPadding = ((uint)(12));
			// Container child APIAlignment.Gtk.Container+ContainerChild
			this.APILayout = new global::Gtk.VBox();
			this.APILayout.Name = "APILayout";
			this.APILayout.Spacing = 6;
			// Container child APILayout.Gtk.Box+BoxChild
			this.CarrierImage = new global::Gtk.Image();
			this.CarrierImage.Name = "CarrierImage";
			this.APILayout.Add(this.CarrierImage);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.APILayout[this.CarrierImage]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child APILayout.Gtk.Box+BoxChild
			this.CarrierDescriptionLabel = new global::Gtk.Label();
			this.CarrierDescriptionLabel.WidthRequest = 512;
			this.CarrierDescriptionLabel.Name = "CarrierDescriptionLabel";
			this.CarrierDescriptionLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Hive carriers can/will support various shipping services such as Amazon Fullfille" +
					"d orders (Amazon Prime).");
			this.CarrierDescriptionLabel.UseMarkup = true;
			this.CarrierDescriptionLabel.Wrap = true;
			this.APILayout.Add(this.CarrierDescriptionLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.APILayout[this.CarrierDescriptionLabel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child APILayout.Gtk.Box+BoxChild
			this.HiveURLLayout = new global::Gtk.HBox();
			this.HiveURLLayout.Name = "HiveURLLayout";
			this.HiveURLLayout.Spacing = 6;
			// Container child HiveURLLayout.Gtk.Box+BoxChild
			this.HiveURLLabel = new global::Gtk.Label();
			this.HiveURLLabel.WidthRequest = 200;
			this.HiveURLLabel.Name = "HiveURLLabel";
			this.HiveURLLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Hive URL");
			this.HiveURLLabel.Wrap = true;
			this.HiveURLLabel.SingleLineMode = true;
			this.HiveURLLayout.Add(this.HiveURLLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.HiveURLLayout[this.HiveURLLabel]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child HiveURLLayout.Gtk.Box+BoxChild
			this.InputHiveURLEntry = new global::Gtk.Entry();
			this.InputHiveURLEntry.TooltipMarkup = "The filename for the Hive input file. This should match the setting on Hive. ";
			this.InputHiveURLEntry.CanFocus = true;
			this.InputHiveURLEntry.Name = "InputHiveURLEntry";
			this.InputHiveURLEntry.IsEditable = true;
			this.InputHiveURLEntry.InvisibleChar = '•';
			this.HiveURLLayout.Add(this.InputHiveURLEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.HiveURLLayout[this.InputHiveURLEntry]));
			w4.Position = 1;
			this.APILayout.Add(this.HiveURLLayout);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.APILayout[this.HiveURLLayout]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child APILayout.Gtk.Box+BoxChild
			this.HiveURLLayout1 = new global::Gtk.HBox();
			this.HiveURLLayout1.Name = "HiveURLLayout1";
			this.HiveURLLayout1.Spacing = 6;
			// Container child HiveURLLayout1.Gtk.Box+BoxChild
			this.PrinterProfileLabel = new global::Gtk.Label();
			this.PrinterProfileLabel.WidthRequest = 200;
			this.PrinterProfileLabel.Name = "PrinterProfileLabel";
			this.PrinterProfileLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Printer Profile");
			this.PrinterProfileLabel.Wrap = true;
			this.PrinterProfileLabel.SingleLineMode = true;
			this.HiveURLLayout1.Add(this.PrinterProfileLabel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.HiveURLLayout1[this.PrinterProfileLabel]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child HiveURLLayout1.Gtk.Box+BoxChild
			this.PrinterProfileSelectionCombo = global::Gtk.ComboBox.NewText();
			this.PrinterProfileSelectionCombo.Name = "PrinterProfileSelectionCombo";
			this.HiveURLLayout1.Add(this.PrinterProfileSelectionCombo);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.HiveURLLayout1[this.PrinterProfileSelectionCombo]));
			w7.Position = 1;
			this.APILayout.Add(this.HiveURLLayout1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.APILayout[this.HiveURLLayout1]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			this.APIAlignment.Add(this.APILayout);
			this.APIFrame.Add(this.APIAlignment);
			this.CarrierLabel = new global::Gtk.Label();
			this.CarrierLabel.Name = "CarrierLabel";
			this.CarrierLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Hive Carrier Settings</b>");
			this.CarrierLabel.UseMarkup = true;
			this.APIFrame.LabelWidget = this.CarrierLabel;
			this.CarrierLayout.Add(this.APIFrame);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.CarrierLayout[this.APIFrame]));
			w11.Position = 0;
			// Container child CarrierLayout.Gtk.Box+BoxChild
			this.HiveDetailsFrame = new global::Gtk.Frame();
			this.HiveDetailsFrame.Name = "HiveDetailsFrame";
			this.HiveDetailsFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child HiveDetailsFrame.Gtk.Container+ContainerChild
			this.HiveDetailsAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.HiveDetailsAlignment.Name = "HiveDetailsAlignment";
			this.HiveDetailsAlignment.LeftPadding = ((uint)(12));
			// Container child HiveDetailsAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.HiveDetailsTextView = new global::Gtk.TextView();
			this.HiveDetailsTextView.TooltipMarkup = "Enter the template used by Hive here. {Tags} will be replaced with order data.";
			this.HiveDetailsTextView.CanFocus = true;
			this.HiveDetailsTextView.Name = "HiveDetailsTextView";
			this.HiveDetailsTextView.AcceptsTab = false;
			this.HiveDetailsTextView.LeftMargin = 4;
			this.HiveDetailsTextView.RightMargin = 4;
			this.GtkScrolledWindow.Add(this.HiveDetailsTextView);
			this.HiveDetailsAlignment.Add(this.GtkScrolledWindow);
			this.HiveDetailsFrame.Add(this.HiveDetailsAlignment);
			this.HiveDetailsLabel = new global::Gtk.Label();
			this.HiveDetailsLabel.Name = "HiveDetailsLabel";
			this.HiveDetailsLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Additional POST Paramters</b>");
			this.HiveDetailsLabel.UseMarkup = true;
			this.HiveDetailsFrame.LabelWidget = this.HiveDetailsLabel;
			this.CarrierLayout.Add(this.HiveDetailsFrame);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.CarrierLayout[this.HiveDetailsFrame]));
			w15.Position = 1;
			// Container child CarrierLayout.Gtk.Box+BoxChild
			this.MainControlsLayout = new global::Gtk.HBox();
			this.MainControlsLayout.Name = "MainControlsLayout";
			this.MainControlsLayout.Spacing = 6;
			// Container child MainControlsLayout.Gtk.Box+BoxChild
			this.MainControlsSpacerAlignment = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.MainControlsSpacerAlignment.Name = "MainControlsSpacerAlignment";
			this.MainControlsLayout.Add(this.MainControlsSpacerAlignment);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.MainControlsLayout[this.MainControlsSpacerAlignment]));
			w16.Position = 0;
			// Container child MainControlsLayout.Gtk.Box+BoxChild
			this.CancelButton = new global::Gtk.Button();
			this.CancelButton.WidthRequest = 150;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = global::Mono.Unix.Catalog.GetString("Cancel");
			global::Gtk.Image w17 = new global::Gtk.Image();
			w17.Pixbuf = new global::Gdk.Pixbuf(global::System.IO.Path.Combine(global::System.AppDomain.CurrentDomain.BaseDirectory, "./Icons/png/no-small.png"));
			this.CancelButton.Image = w17;
			this.MainControlsLayout.Add(this.CancelButton);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.MainControlsLayout[this.CancelButton]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child MainControlsLayout.Gtk.Box+BoxChild
			this.ConfirmButton = new global::Gtk.Button();
			this.ConfirmButton.WidthRequest = 150;
			this.ConfirmButton.CanFocus = true;
			this.ConfirmButton.Name = "ConfirmButton";
			this.ConfirmButton.UseUnderline = true;
			this.ConfirmButton.Label = global::Mono.Unix.Catalog.GetString("Ok");
			global::Gtk.Image w19 = new global::Gtk.Image();
			w19.Pixbuf = new global::Gdk.Pixbuf(global::System.IO.Path.Combine(global::System.AppDomain.CurrentDomain.BaseDirectory, "./Icons/png/apply-small.png"));
			this.ConfirmButton.Image = w19;
			this.MainControlsLayout.Add(this.ConfirmButton);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.MainControlsLayout[this.ConfirmButton]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.CarrierLayout.Add(this.MainControlsLayout);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.CarrierLayout[this.MainControlsLayout]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.Add(this.CarrierLayout);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 560;
			this.DefaultHeight = 353;
			this.Show();
			this.CancelButton.Released += new global::System.EventHandler(this.OnCancelButtonReleased);
			this.ConfirmButton.Released += new global::System.EventHandler(this.OnConfirmButtonReleased);
		}
	}
}
