//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace UberDespatch.PvxApi {
	using System;
	using System.Web.Services;
	using System.Diagnostics;
	using System.Web.Services.Protocols;
	using System.Xml.Serialization;
	using System.ComponentModel;


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="IntegrationServiceV4Soap", Namespace="http://www.peoplevox.net/")]
	public partial class IntegrationServiceV4 : System.Web.Services.Protocols.SoapHttpClientProtocol {

		private System.Threading.SendOrPostCallback AuthenticateOperationCompleted;

		private UserSessionCredentials userSessionCredentialsValueField;

		private System.Threading.SendOrPostCallback GetDataOperationCompleted;

		private System.Threading.SendOrPostCallback GetReportDataOperationCompleted;

		private System.Threading.SendOrPostCallback GetSaveTemplateOperationCompleted;

		private System.Threading.SendOrPostCallback SaveDataOperationCompleted;

		private System.Threading.SendOrPostCallback SubscribeEventOperationCompleted;

		private System.Threading.SendOrPostCallback SubscribePostEventOperationCompleted;

		private System.Threading.SendOrPostCallback UnsubscribeEventOperationCompleted;

		private bool useDefaultCredentialsSetExplicitly;

		/// <remarks/>
		public IntegrationServiceV4() {
			this.Url = "http://peoplevox.net/appb/resources/integrationservicev4.asmx";
			if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
				this.UseDefaultCredentials = true;
				this.useDefaultCredentialsSetExplicitly = false;
			}
			else {
				this.useDefaultCredentialsSetExplicitly = true;
			}
		}

		public UserSessionCredentials UserSessionCredentialsValue {
			get {
				return this.userSessionCredentialsValueField;
			}
			set {
				this.userSessionCredentialsValueField = value;
			}
		}

		public new string Url {
			get {
				return base.Url;
			}
			set {
				if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
					&& (this.useDefaultCredentialsSetExplicitly == false)) 
					&& (this.IsLocalFileSystemWebService(value) == false))) {
					base.UseDefaultCredentials = false;
				}
				base.Url = value;
			}
		}

		public new bool UseDefaultCredentials {
			get {
				return base.UseDefaultCredentials;
			}
			set {
				base.UseDefaultCredentials = value;
				this.useDefaultCredentialsSetExplicitly = true;
			}
		}

		/// <remarks/>
		public event AuthenticateCompletedEventHandler AuthenticateCompleted;

		/// <remarks/>
		public event GetDataCompletedEventHandler GetDataCompleted;

		/// <remarks/>
		public event GetReportDataCompletedEventHandler GetReportDataCompleted;

		/// <remarks/>
		public event GetSaveTemplateCompletedEventHandler GetSaveTemplateCompleted;

		/// <remarks/>
		public event SaveDataCompletedEventHandler SaveDataCompleted;

		/// <remarks/>
		public event SubscribeEventCompletedEventHandler SubscribeEventCompleted;

		/// <remarks/>
		public event SubscribePostEventCompletedEventHandler SubscribePostEventCompleted;

		/// <remarks/>
		public event UnsubscribeEventCompletedEventHandler UnsubscribeEventCompleted;

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.peoplevox.net/Authenticate", RequestNamespace="http://www.peoplevox.net/", ResponseNamespace="http://www.peoplevox.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public IntegrationResponse Authenticate(string clientId, string username, string password) {
			object[] results = this.Invoke("Authenticate", new object[] {
				clientId,
				username,
				password});
			return ((IntegrationResponse)(results[0]));
		}

		/// <remarks/>
		public void AuthenticateAsync(string clientId, string username, string password) {
			this.AuthenticateAsync(clientId, username, password, null);
		}

		/// <remarks/>
		public void AuthenticateAsync(string clientId, string username, string password, object userState) {
			if ((this.AuthenticateOperationCompleted == null)) {
				this.AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateOperationCompleted);
			}
			this.InvokeAsync("Authenticate", new object[] {
				clientId,
				username,
				password}, this.AuthenticateOperationCompleted, userState);
		}

		private void OnAuthenticateOperationCompleted(object arg) {
			if ((this.AuthenticateCompleted != null)) {
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapHeaderAttribute("UserSessionCredentialsValue")]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.peoplevox.net/GetData", RequestNamespace="http://www.peoplevox.net/", ResponseNamespace="http://www.peoplevox.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public IntegrationResponse GetData(GetRequest getRequest) {
			object[] results = this.Invoke("GetData", new object[] {
				getRequest});
			return ((IntegrationResponse)(results[0]));
		}

		/// <remarks/>
		public void GetDataAsync(GetRequest getRequest) {
			this.GetDataAsync(getRequest, null);
		}

		/// <remarks/>
		public void GetDataAsync(GetRequest getRequest, object userState) {
			if ((this.GetDataOperationCompleted == null)) {
				this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
			}
			this.InvokeAsync("GetData", new object[] {
				getRequest}, this.GetDataOperationCompleted, userState);
		}

		private void OnGetDataOperationCompleted(object arg) {
			if ((this.GetDataCompleted != null)) {
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapHeaderAttribute("UserSessionCredentialsValue")]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.peoplevox.net/GetReportData", RequestNamespace="http://www.peoplevox.net/", ResponseNamespace="http://www.peoplevox.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public IntegrationResponse GetReportData(GetReportRequest getReportRequest) {
			object[] results = this.Invoke("GetReportData", new object[] {
				getReportRequest});
			return ((IntegrationResponse)(results[0]));
		}

		/// <remarks/>
		public void GetReportDataAsync(GetReportRequest getReportRequest) {
			this.GetReportDataAsync(getReportRequest, null);
		}

		/// <remarks/>
		public void GetReportDataAsync(GetReportRequest getReportRequest, object userState) {
			if ((this.GetReportDataOperationCompleted == null)) {
				this.GetReportDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportDataOperationCompleted);
			}
			this.InvokeAsync("GetReportData", new object[] {
				getReportRequest}, this.GetReportDataOperationCompleted, userState);
		}

		private void OnGetReportDataOperationCompleted(object arg) {
			if ((this.GetReportDataCompleted != null)) {
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.GetReportDataCompleted(this, new GetReportDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapHeaderAttribute("UserSessionCredentialsValue")]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.peoplevox.net/GetSaveTemplate", RequestNamespace="http://www.peoplevox.net/", ResponseNamespace="http://www.peoplevox.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public IntegrationResponse GetSaveTemplate(string templateName) {
			object[] results = this.Invoke("GetSaveTemplate", new object[] {
				templateName});
			return ((IntegrationResponse)(results[0]));
		}

		/// <remarks/>
		public void GetSaveTemplateAsync(string templateName) {
			this.GetSaveTemplateAsync(templateName, null);
		}

		/// <remarks/>
		public void GetSaveTemplateAsync(string templateName, object userState) {
			if ((this.GetSaveTemplateOperationCompleted == null)) {
				this.GetSaveTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSaveTemplateOperationCompleted);
			}
			this.InvokeAsync("GetSaveTemplate", new object[] {
				templateName}, this.GetSaveTemplateOperationCompleted, userState);
		}

		private void OnGetSaveTemplateOperationCompleted(object arg) {
			if ((this.GetSaveTemplateCompleted != null)) {
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.GetSaveTemplateCompleted(this, new GetSaveTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapHeaderAttribute("UserSessionCredentialsValue")]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.peoplevox.net/SaveData", RequestNamespace="http://www.peoplevox.net/", ResponseNamespace="http://www.peoplevox.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public IntegrationResponse SaveData(SaveRequest saveRequest) {
			object[] results = this.Invoke("SaveData", new object[] {
				saveRequest});
			return ((IntegrationResponse)(results[0]));
		}

		/// <remarks/>
		public void SaveDataAsync(SaveRequest saveRequest) {
			this.SaveDataAsync(saveRequest, null);
		}

		/// <remarks/>
		public void SaveDataAsync(SaveRequest saveRequest, object userState) {
			if ((this.SaveDataOperationCompleted == null)) {
				this.SaveDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveDataOperationCompleted);
			}
			this.InvokeAsync("SaveData", new object[] {
				saveRequest}, this.SaveDataOperationCompleted, userState);
		}

		private void OnSaveDataOperationCompleted(object arg) {
			if ((this.SaveDataCompleted != null)) {
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.SaveDataCompleted(this, new SaveDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapHeaderAttribute("UserSessionCredentialsValue")]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.peoplevox.net/SubscribeEvent", RequestNamespace="http://www.peoplevox.net/", ResponseNamespace="http://www.peoplevox.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public IntegrationResponse SubscribeEvent(SubscriptionEventTypes eventType, string filter, string callbackUrl) {
			object[] results = this.Invoke("SubscribeEvent", new object[] {
				eventType,
				filter,
				callbackUrl});
			return ((IntegrationResponse)(results[0]));
		}

		/// <remarks/>
		public void SubscribeEventAsync(SubscriptionEventTypes eventType, string filter, string callbackUrl) {
			this.SubscribeEventAsync(eventType, filter, callbackUrl, null);
		}

		/// <remarks/>
		public void SubscribeEventAsync(SubscriptionEventTypes eventType, string filter, string callbackUrl, object userState) {
			if ((this.SubscribeEventOperationCompleted == null)) {
				this.SubscribeEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubscribeEventOperationCompleted);
			}
			this.InvokeAsync("SubscribeEvent", new object[] {
				eventType,
				filter,
				callbackUrl}, this.SubscribeEventOperationCompleted, userState);
		}

		private void OnSubscribeEventOperationCompleted(object arg) {
			if ((this.SubscribeEventCompleted != null)) {
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.SubscribeEventCompleted(this, new SubscribeEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapHeaderAttribute("UserSessionCredentialsValue")]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.peoplevox.net/SubscribePostEvent", RequestNamespace="http://www.peoplevox.net/", ResponseNamespace="http://www.peoplevox.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public IntegrationResponse SubscribePostEvent(SubscriptionEventTypes eventType, string filter, string postUrl, string postParams) {
			object[] results = this.Invoke("SubscribePostEvent", new object[] {
				eventType,
				filter,
				postUrl,
				postParams});
			return ((IntegrationResponse)(results[0]));
		}

		/// <remarks/>
		public void SubscribePostEventAsync(SubscriptionEventTypes eventType, string filter, string postUrl, string postParams) {
			this.SubscribePostEventAsync(eventType, filter, postUrl, postParams, null);
		}

		/// <remarks/>
		public void SubscribePostEventAsync(SubscriptionEventTypes eventType, string filter, string postUrl, string postParams, object userState) {
			if ((this.SubscribePostEventOperationCompleted == null)) {
				this.SubscribePostEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubscribePostEventOperationCompleted);
			}
			this.InvokeAsync("SubscribePostEvent", new object[] {
				eventType,
				filter,
				postUrl,
				postParams}, this.SubscribePostEventOperationCompleted, userState);
		}

		private void OnSubscribePostEventOperationCompleted(object arg) {
			if ((this.SubscribePostEventCompleted != null)) {
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.SubscribePostEventCompleted(this, new SubscribePostEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapHeaderAttribute("UserSessionCredentialsValue")]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.peoplevox.net/UnsubscribeEvent", RequestNamespace="http://www.peoplevox.net/", ResponseNamespace="http://www.peoplevox.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public IntegrationResponse UnsubscribeEvent(int subscriptionId) {
			object[] results = this.Invoke("UnsubscribeEvent", new object[] {
				subscriptionId});
			return ((IntegrationResponse)(results[0]));
		}

		/// <remarks/>
		public void UnsubscribeEventAsync(int subscriptionId) {
			this.UnsubscribeEventAsync(subscriptionId, null);
		}

		/// <remarks/>
		public void UnsubscribeEventAsync(int subscriptionId, object userState) {
			if ((this.UnsubscribeEventOperationCompleted == null)) {
				this.UnsubscribeEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnsubscribeEventOperationCompleted);
			}
			this.InvokeAsync("UnsubscribeEvent", new object[] {
				subscriptionId}, this.UnsubscribeEventOperationCompleted, userState);
		}

		private void OnUnsubscribeEventOperationCompleted(object arg) {
			if ((this.UnsubscribeEventCompleted != null)) {
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.UnsubscribeEventCompleted(this, new UnsubscribeEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		public new void CancelAsync(object userState) {
			base.CancelAsync(userState);
		}

		private bool IsLocalFileSystemWebService(string url) {
			if (((url == null) 
				|| (url == string.Empty))) {
				return false;
			}
			System.Uri wsUri = new System.Uri(url);
			if (((wsUri.Port >= 1024) 
				&& (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
				return true;
			}
			return false;
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peoplevox.net/")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.peoplevox.net/", IsNullable=false)]
	public partial class UserSessionCredentials : System.Web.Services.Protocols.SoapHeader {

		private System.Nullable<int> userIdField;

		private string clientIdField;

		private string sessionIdField;

		private System.Xml.XmlAttribute[] anyAttrField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
		public System.Nullable<int> UserId {
			get {
				return this.userIdField;
			}
			set {
				this.userIdField = value;
			}
		}

		/// <remarks/>
		public string ClientId {
			get {
				return this.clientIdField;
			}
			set {
				this.clientIdField = value;
			}
		}

		/// <remarks/>
		public string SessionId {
			get {
				return this.sessionIdField;
			}
			set {
				this.sessionIdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAnyAttributeAttribute()]
		public System.Xml.XmlAttribute[] AnyAttr {
			get {
				return this.anyAttrField;
			}
			set {
				this.anyAttrField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peoplevox.net/")]
	public partial class SaveRequest {

		private string templateNameField;

		private string csvDataField;

		private int actionField;

		/// <remarks/>
		public string TemplateName {
			get {
				return this.templateNameField;
			}
			set {
				this.templateNameField = value;
			}
		}

		/// <remarks/>
		public string CsvData {
			get {
				return this.csvDataField;
			}
			set {
				this.csvDataField = value;
			}
		}

		/// <remarks/>
		public int Action {
			get {
				return this.actionField;
			}
			set {
				this.actionField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetReportRequest))]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peoplevox.net/")]
	public partial class GetRequest {

		private string templateNameField;

		private int pageNoField;

		private int itemsPerPageField;

		private string searchClauseField;

		/// <remarks/>
		public string TemplateName {
			get {
				return this.templateNameField;
			}
			set {
				this.templateNameField = value;
			}
		}

		/// <remarks/>
		public int PageNo {
			get {
				return this.pageNoField;
			}
			set {
				this.pageNoField = value;
			}
		}

		/// <remarks/>
		public int ItemsPerPage {
			get {
				return this.itemsPerPageField;
			}
			set {
				this.itemsPerPageField = value;
			}
		}

		/// <remarks/>
		public string SearchClause {
			get {
				return this.searchClauseField;
			}
			set {
				this.searchClauseField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peoplevox.net/")]
	public partial class GetReportRequest : GetRequest {

		private string filterClauseField;

		private string orderByField;

		private string columnsField;

		/// <remarks/>
		public string FilterClause {
			get {
				return this.filterClauseField;
			}
			set {
				this.filterClauseField = value;
			}
		}

		/// <remarks/>
		public string OrderBy {
			get {
				return this.orderByField;
			}
			set {
				this.orderByField = value;
			}
		}

		/// <remarks/>
		public string Columns {
			get {
				return this.columnsField;
			}
			set {
				this.columnsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peoplevox.net/")]
	public partial class IntegrationStatusResponse {

		private string referenceField;

		private IntegrationResponseStatuses statusField;

		/// <remarks/>
		public string Reference {
			get {
				return this.referenceField;
			}
			set {
				this.referenceField = value;
			}
		}

		/// <remarks/>
		public IntegrationResponseStatuses Status {
			get {
				return this.statusField;
			}
			set {
				this.statusField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peoplevox.net/")]
	public enum IntegrationResponseStatuses {

		/// <remarks/>
		Error,

		/// <remarks/>
		Success,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peoplevox.net/")]
	public partial class IntegrationResponse {

		private int responseIdField;

		private int totalCountField;

		private string detailField;

		private IntegrationStatusResponse[] statusesField;

		/// <remarks/>
		public int ResponseId {
			get {
				return this.responseIdField;
			}
			set {
				this.responseIdField = value;
			}
		}

		/// <remarks/>
		public int TotalCount {
			get {
				return this.totalCountField;
			}
			set {
				this.totalCountField = value;
			}
		}

		/// <remarks/>
		public string Detail {
			get {
				return this.detailField;
			}
			set {
				this.detailField = value;
			}
		}

		/// <remarks/>
		public IntegrationStatusResponse[] Statuses {
			get {
				return this.statusesField;
			}
			set {
				this.statusesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.peoplevox.net/")]
	public enum SubscriptionEventTypes {

		/// <remarks/>
		AvailabilityChanges,

		/// <remarks/>
		SalesOrderStatusChanges,

		/// <remarks/>
		GoodsReceived,

		/// <remarks/>
		TrackingNumberReceived,

		/// <remarks/>
		IncrementalChanges,

		/// <remarks/>
		Returns,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	public delegate void AuthenticateCompletedEventHandler(object sender, AuthenticateCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

		private object[] results;

		internal AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
		base(exception, cancelled, userState) {
			this.results = results;
		}

		/// <remarks/>
		public IntegrationResponse Result {
			get {
				this.RaiseExceptionIfNecessary();
				return ((IntegrationResponse)(this.results[0]));
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

		private object[] results;

		internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
		base(exception, cancelled, userState) {
			this.results = results;
		}

		/// <remarks/>
		public IntegrationResponse Result {
			get {
				this.RaiseExceptionIfNecessary();
				return ((IntegrationResponse)(this.results[0]));
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	public delegate void GetReportDataCompletedEventHandler(object sender, GetReportDataCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GetReportDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

		private object[] results;

		internal GetReportDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
		base(exception, cancelled, userState) {
			this.results = results;
		}

		/// <remarks/>
		public IntegrationResponse Result {
			get {
				this.RaiseExceptionIfNecessary();
				return ((IntegrationResponse)(this.results[0]));
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	public delegate void GetSaveTemplateCompletedEventHandler(object sender, GetSaveTemplateCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GetSaveTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

		private object[] results;

		internal GetSaveTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
		base(exception, cancelled, userState) {
			this.results = results;
		}

		/// <remarks/>
		public IntegrationResponse Result {
			get {
				this.RaiseExceptionIfNecessary();
				return ((IntegrationResponse)(this.results[0]));
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	public delegate void SaveDataCompletedEventHandler(object sender, SaveDataCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class SaveDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

		private object[] results;

		internal SaveDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
		base(exception, cancelled, userState) {
			this.results = results;
		}

		/// <remarks/>
		public IntegrationResponse Result {
			get {
				this.RaiseExceptionIfNecessary();
				return ((IntegrationResponse)(this.results[0]));
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	public delegate void SubscribeEventCompletedEventHandler(object sender, SubscribeEventCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class SubscribeEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

		private object[] results;

		internal SubscribeEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
		base(exception, cancelled, userState) {
			this.results = results;
		}

		/// <remarks/>
		public IntegrationResponse Result {
			get {
				this.RaiseExceptionIfNecessary();
				return ((IntegrationResponse)(this.results[0]));
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	public delegate void SubscribePostEventCompletedEventHandler(object sender, SubscribePostEventCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class SubscribePostEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

		private object[] results;

		internal SubscribePostEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
		base(exception, cancelled, userState) {
			this.results = results;
		}

		/// <remarks/>
		public IntegrationResponse Result {
			get {
				this.RaiseExceptionIfNecessary();
				return ((IntegrationResponse)(this.results[0]));
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	public delegate void UnsubscribeEventCompletedEventHandler(object sender, UnsubscribeEventCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class UnsubscribeEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

		private object[] results;

		internal UnsubscribeEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
		base(exception, cancelled, userState) {
			this.results = results;
		}

		/// <remarks/>
		public IntegrationResponse Result {
			get {
				this.RaiseExceptionIfNecessary();
				return ((IntegrationResponse)(this.results[0]));
			}
		}
	}
}

#pragma warning restore 1591